import './global.css';
import styles from './layout.module.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import Link from 'next/link';
import { WithStore } from '@/data';

const sanchez = Roboto({ weight: "400", subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Division III Men's Collegiate Lacrosse 2023 Draft Auction",
  description: 'Not generated by create next app',
};

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body className={`${sanchez.className} ${styles.body}`}>
        <nav className={styles.nav}>
          <ul>
            <li><Link href="/auction">Auction</Link></li>
            <li><Link href="/players">Players</Link></li>
          </ul>
        </nav>
        <WithStore>
          {children}
        </WithStore>
      </body>
    </html>
  );
};
